import type { Book } from "../types";

// Shared discover books data
export const DISCOVER_BOOKS: Book[] = [
  {
    id: "discover-1",
    title: "The House in the Cerulean Sea",
    author: "TJ Klune",
    authors: ["TJ Klune"],
    cover: "https://covers.openlibrary.org/b/isbn/9781250217288-L.jpg",
    description:
      "A magical story about found family and love in unexpected places.",
    pages: 400,
    publishYear: 2020,
    subjects: ["Fantasy", "LGBTQ+", "Feel-good"],
    languages: ["English"],
    isbn: "9781250217288",
    rating: 4.5,
    openLibraryKey: "discover-1",
  },
  {
    id: "discover-2",
    title: "The Silent Patient",
    author: "Alex Michaelides",
    authors: ["Alex Michaelides"],
    cover: "https://covers.openlibrary.org/b/isbn/9781250301697-L.jpg",
    description:
      "A woman refuses to speak after allegedly murdering her husband.",
    pages: 352,
    publishYear: 2019,
    subjects: ["Thriller", "Mystery", "Psychological"],
    languages: ["English"],
    isbn: "9781250301697",
    rating: 4.2,
    openLibraryKey: "discover-2",
  },
  {
    id: "discover-3",
    title: "Educated",
    author: "Tara Westover",
    authors: ["Tara Westover"],
    cover: "https://covers.openlibrary.org/b/isbn/9780399590504-L.jpg",
    description: "A powerful memoir about education and family.",
    pages: 334,
    publishYear: 2018,
    subjects: ["Memoir", "Biography", "Education"],
    languages: ["English"],
    isbn: "9780399590504",
    rating: 4.4,
    openLibraryKey: "discover-3",
  },
  {
    id: "discover-4",
    title: "Where the Crawdads Sing",
    author: "Delia Owens",
    authors: ["Delia Owens"],
    cover: "https://covers.openlibrary.org/b/isbn/9780735219090-L.jpg",
    description:
      "A mystery about a young woman who raised herself in the marshes.",
    pages: 370,
    publishYear: 2018,
    subjects: ["Historical Fiction", "Mystery", "Nature"],
    languages: ["English"],
    isbn: "9780735219090",
    rating: 4.3,
    openLibraryKey: "discover-4",
  },
  {
    id: "discover-5",
    title: "The Seven Husbands of Evelyn Hugo",
    author: "Taylor Jenkins Reid",
    authors: ["Taylor Jenkins Reid"],
    cover: "https://covers.openlibrary.org/b/isbn/9781501161933-L.jpg",
    description:
      "A reclusive Hollywood icon finally tells her story to a young journalist.",
    pages: 400,
    publishYear: 2017,
    subjects: ["Historical Fiction", "Romance"],
    languages: ["English"],
    isbn: "9781501161933",
    rating: 4.2,
    openLibraryKey: "discover-5",
  },
  {
    id: "discover-6",
    title: "Atomic Habits",
    author: "James Clear",
    authors: ["James Clear"],
    cover: "https://covers.openlibrary.org/b/isbn/9780735211292-L.jpg",
    description: "An easy & proven way to build good habits & break bad ones.",
    pages: 320,
    publishYear: 2018,
    subjects: ["Self-help", "Psychology", "Productivity"],
    languages: ["English"],
    isbn: "9780735211292",
    rating: 4.4,
    openLibraryKey: "discover-6",
  },
  {
    id: "discover-7",
    title: "The Midnight Library",
    author: "Matt Haig",
    authors: ["Matt Haig"],
    cover: "https://covers.openlibrary.org/b/isbn/9780525559474-L.jpg",
    description:
      "A novel about all the choices that go into a life well lived.",
    pages: 288,
    publishYear: 2020,
    subjects: ["Literary Fiction", "Philosophy", "Self-discovery"],
    languages: ["English"],
    isbn: "9780525559474",
    rating: 4.1,
    openLibraryKey: "discover-7",
  },
  {
    id: "discover-8",
    title: "Klara and the Sun",
    author: "Kazuo Ishiguro",
    authors: ["Kazuo Ishiguro"],
    cover: "https://covers.openlibrary.org/b/isbn/9780593318171-L.jpg",
    description: "A story told from the perspective of an artificial friend.",
    pages: 303,
    publishYear: 2021,
    subjects: ["Science Fiction", "Literary Fiction", "AI"],
    languages: ["English"],
    isbn: "9780593318171",
    rating: 4.0,
    openLibraryKey: "discover-8",
  },
  {
    id: "discover-9",
    title: "The Guest List",
    author: "Lucy Foley",
    authors: ["Lucy Foley"],
    cover: "https://covers.openlibrary.org/b/isbn/9780062868930-L.jpg",
    description:
      "A wedding celebration turns dark and deadly in this twisted psychological thriller.",
    pages: 320,
    publishYear: 2020,
    subjects: ["Thriller", "Mystery", "Psychological"],
    languages: ["English"],
    isbn: "9780062868930",
    rating: 4.1,
    openLibraryKey: "discover-9",
  },
  {
    id: "discover-10",
    title: "Circe",
    author: "Madeline Miller",
    authors: ["Madeline Miller"],
    cover: "https://covers.openlibrary.org/b/isbn/9780316556347-L.jpg",
    description: "The story of the witch from Homer's Odyssey.",
    pages: 393,
    publishYear: 2018,
    subjects: ["Fantasy", "Mythology", "Historical Fiction"],
    languages: ["English"],
    isbn: "9780316556347",
    rating: 4.3,
    openLibraryKey: "discover-10",
  },
  {
    id: "discover-11",
    title: "The Invisible Life of Addie LaRue",
    author: "V.E. Schwab",
    authors: ["V.E. Schwab"],
    cover: "https://covers.openlibrary.org/b/isbn/9780765387561-L.jpg",
    description: "A woman cursed to be forgotten by everyone she meets.",
    pages: 560,
    publishYear: 2020,
    subjects: ["Fantasy", "Romance", "Historical Fiction"],
    languages: ["English"],
    isbn: "9780765387561",
    rating: 4.2,
    openLibraryKey: "discover-11",
  },
  {
    id: "discover-12",
    title: "Project Hail Mary",
    author: "Andy Weir",
    authors: ["Andy Weir"],
    cover: "https://covers.openlibrary.org/b/isbn/9780593135204-L.jpg",
    description:
      "A lone astronaut must save humanity in this thrilling space adventure.",
    pages: 496,
    publishYear: 2021,
    subjects: ["Science Fiction", "Space", "Adventure"],
    languages: ["English"],
    isbn: "9780593135204",
    rating: 4.5,
    openLibraryKey: "discover-12",
  },
  {
    id: "discover-13",
    title: "The Thursday Murder Club",
    author: "Richard Osman",
    authors: ["Richard Osman"],
    cover: "https://covers.openlibrary.org/b/isbn/9781984880987-L.jpg",
    description:
      "Four unlikely friends investigate cold cases in their retirement home.",
    pages: 368,
    publishYear: 2020,
    subjects: ["Mystery", "Humor", "Crime"],
    languages: ["English"],
    isbn: "9781984880987",
    rating: 4.2,
    openLibraryKey: "discover-13",
  },
  {
    id: "discover-14",
    title: "The Sanatorium",
    author: "Sarah Pearse",
    authors: ["Sarah Pearse"],
    cover: "https://covers.openlibrary.org/b/isbn/9780593296677-L.jpg",
    description: "A detective investigates a disappearance at a remote hotel.",
    pages: 352,
    publishYear: 2021,
    subjects: ["Thriller", "Mystery", "Suspense"],
    languages: ["English"],
    isbn: "9780593296677",
    rating: 3.9,
    openLibraryKey: "discover-14",
  },
  {
    id: "discover-15",
    title: "The Four Winds",
    author: "Kristin Hannah",
    authors: ["Kristin Hannah"],
    cover: "https://covers.openlibrary.org/b/isbn/9781250178602-L.jpg",
    description: "A powerful story of resilience during the Great Depression.",
    pages: 454,
    publishYear: 2021,
    subjects: ["Historical Fiction", "Family", "Drama"],
    languages: ["English"],
    isbn: "9781250178602",
    rating: 4.3,
    openLibraryKey: "discover-15",
  },
  {
    id: "discover-16",
    title: "Mexican Gothic",
    author: "Silvia Moreno-Garcia",
    authors: ["Silvia Moreno-Garcia"],
    cover: "https://covers.openlibrary.org/b/isbn/9780525620785-L.jpg",
    description:
      "A young woman encounters terrors at a decaying English manor in 1950s Mexico.",
    pages: 301,
    publishYear: 2020,
    subjects: ["Gothic", "Horror", "Historical Fiction"],
    languages: ["English"],
    isbn: "9780525620785",
    rating: 4.0,
    openLibraryKey: "discover-16",
  },
  {
    id: "discover-17",
    title: "The Vanishing Half",
    author: "Brit Bennett",
    authors: ["Brit Bennett"],
    cover: "https://covers.openlibrary.org/b/isbn/9780525536291-L.jpg",
    description:
      "The story of twin sisters who choose to live in very different worlds.",
    pages: 352,
    publishYear: 2020,
    subjects: ["Literary Fiction", "Family", "Identity"],
    languages: ["English"],
    isbn: "9780525536291",
    rating: 4.2,
    openLibraryKey: "discover-17",
  },
  {
    id: "discover-18",
    title: "The Push",
    author: "Ashley Audrain",
    authors: ["Ashley Audrain"],
    cover: "https://covers.openlibrary.org/b/isbn/9780593087251-L.jpg",
    description:
      "A psychological thriller about motherhood and family secrets.",
    pages: 320,
    publishYear: 2021,
    subjects: ["Psychological Thriller", "Family", "Drama"],
    languages: ["English"],
    isbn: "9780593087251",
    rating: 3.8,
    openLibraryKey: "discover-18",
  },
];

// Function to get a discover book by ID
export function getDiscoverBookById(id: string): Book | undefined {
  return DISCOVER_BOOKS.find((book) => book.id === id);
}

// Function to get all discover books
export function getAllDiscoverBooks(): Book[] {
  return DISCOVER_BOOKS;
}
